spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invernadero
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mongodb:
      uri: mongodb+srv://backend_user:Invernadero123@greenhouse-cluster.qr22rhi.mongodb.net/invernadero_db?appName=greenhouse-cluster


jwt:
  secret: Znfc8uGSMPo28/dDGxze38e/0WuCEsZR+gXxSBdVlXw=

mqtt:
  url: ssl://p9471c80.ala.us-east-1.emqxsl.com:8883
  client-id: backend-invernadero
  username: test
  password: test123
  topic-in: invernadero/#