spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invernadero
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  mongodb:
      uri: mongodb://localhost:27017/invernadero


jwt:
  secret: Znfc8uGSMPo28/dDGxze38e/0WuCEsZR+gXxSBdVlXw=

mqtt:
  host: ssl://u19791c4.ala.us-east-1.emqxsl.com
  port: 8883
  username: ${MQTT_USERNAME:user_iot}
  password: ${MQTT_PASSWORD:iot1234}
  clientId: backend-greenhouse
